# Generated by Django 3.2.18 on 2023-04-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='task_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
